-- DROP TABLE FIT_FILE;

CREATE TABLE IF NOT EXISTS ACTIVITY (id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, strava_id INT NOT NULL, 
	external_id varchar(255), name varchar(255));

CREATE INDEX IF NOT EXISTS idx_activity_name ON activity(name);

CREATE TABLE IF NOT EXISTS FIT_FILE (ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), 
	UPLOADED BOOLEAN, TOTAL_TIME_IN_SECONDS FLOAT, AVG_SPEED_IN_METERS_PER_SECOND FLOAT, TOTAL_DISTANCE_IN_METERS FLOAT, 
	AVG_HEART_BPM SMALLINT, TIME_CREATED binary(255), START_TIME binary(255), PRODUCT_ID VARCHAR(255), SERIAL_NUMBER VARCHAR (255), SPORT VARCHAR(255));
	
CREATE INDEX IF NOT EXISTS idx_fit_file_name ON activity(name);
