--DROP TABLE FIT_FILE;

--DROP TABLE ACTIVITY;

--DROP TABLE USER;

CREATE TABLE IF NOT EXISTS ACTIVITY (id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, strava_id BIGINT NOT NULL, 
	external_id varchar(255), name varchar(255), STRAVA_USER_ID VARCHAR(255), USER_ID BIGINT, STRAVA_ID BIGINT);

CREATE INDEX IF NOT EXISTS idx_activity_name ON activity(name);

CREATE TABLE IF NOT EXISTS FIT_FILE (ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), 
	UPLOADED BOOLEAN, TOTAL_TIME_IN_SECONDS FLOAT, AVG_SPEED_IN_METERS_PER_SECOND FLOAT, TOTAL_DISTANCE_IN_METERS FLOAT, 
	AVG_HEART_BPM SMALLINT, TIME_CREATED timestamp, START_TIME timestamp, PRODUCT_ID VARCHAR(255), SERIAL_NUMBER VARCHAR (255), SPORT VARCHAR(255), STATUS VARCHAR(50), USER_ID BIGINT);
	
CREATE TABLE IF NOT EXISTS USER (ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, username VARCHAR(255), STRAVA_USER_ID VARCHAR(255),ACCESS_TOKEN VARCHAR(255)); 	
	
CREATE INDEX IF NOT EXISTS idx_fit_file_name ON activity(name);
